name: Deployment Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

        
      - name: Install Dependencies
        run: |
          cd App
          npm i
          if ! git diff --quiet --exit-code HEAD^ -- /.github/; then
            echo "Changes detected in src directory, proceeding with build..."
          else
            echo "No changes detected in src directory, skipping build."
          fi
     